# Generated by Django 4.0.2 on 2022-03-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_techuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='techuser',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='techuser',
            name='updated_at',
        ),
    ]
