# Generated by Django 4.0.2 on 2022-03-14 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_techuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techuser',
            name='role',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.role'),
        ),
    ]
