# Generated by Django 4.0.2 on 2022-03-21 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qna', '0003_question_created_at_question_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('answer', models.CharField(max_length=2000)),
                ('likecount', models.IntegerField()),
                ('dislikecount', models.IntegerField()),
                ('markAsSolution', models.IntegerField(choices=[(0, 'Pending'), (1, 'Correct')], default=0)),
                ('queid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qna.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'answers',
            },
        ),
    ]
