# Generated by Django 4.0.2 on 2022-03-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='dislikecount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='likecount',
            field=models.IntegerField(default=0),
        ),
    ]
