# Generated by Django 4.0.2 on 2022-04-05 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qna', '0005_alter_answer_dislikecount_alter_answer_likecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='likecount',
        ),
        migrations.AddField(
            model_name='answer',
            name='likecount',
            field=models.ManyToManyField(blank=True, related_name='qustion_answer', to=settings.AUTH_USER_MODEL),
        ),
    ]
