# Generated by Django 4.0.2 on 2022-04-06 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qna', '0006_remove_answer_likecount_answer_likecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='dislikecount',
        ),
        migrations.AddField(
            model_name='answer',
            name='dislikecount',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='likecount',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
