# Generated by Django 4.0.2 on 2022-04-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0007_remove_answer_dislikecount_answer_dislikecount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='dislikecount',
        ),
        migrations.AddField(
            model_name='answer',
            name='dislikecount',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='likecount',
        ),
        migrations.AddField(
            model_name='answer',
            name='likecount',
            field=models.IntegerField(default=0),
        ),
    ]
